[[headers]]
for = "/*.nocache.*"
[headers.values]
Cache-Control = "no-cache"


[[headers]]
for = "/*.immut.*"
[headers.values]
Cache-Control = "public, max-age=2592000, immutable"


[[headers]]
for = "/*:!/*.nocache.*:!/*.immut.*"
[headers.values]
Cache-Control = "public, max-age=3600, stale-while-revalidate=31536000"
s-maxage = "3600"


[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "https://the-learning-room.netlify.app,http://localhost:3000,http://127.0.0.1:3000"
Access-Control-Allow-Methods = "GET, OPTIONS"
Access-Control-Allow-Headers = "Content-Type"
Access-Control-Max-Age = "86400"

