[[headers]]
for = "/*.nocache.*"
[headers.values]
Cache-Control = "no-cache"
[[headers]]
for = "/*.immut.*"
[headers.values]
Cache-Control = "public, max-age=2592000, immutable"
[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=3600, stale-while-revalidate=31536000"
s-maxage = "3600"
